package th.co.tpcc.model;
// Generated Oct 28, 2016 10:37:03 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import th.co.baiwa.common.persistence.entity.BaseDomain;

/**
 * SysMessage generated by hbm2java
 */
public class SysMessage extends BaseDomain{

	private Integer messageId;
	private String messageCode;
	private String messageEn;
	private String messageTh;
	private String messageType;
	private String activeFlg;

	public SysMessage() {
	}

	public SysMessage(String messageCode, String messageEn, String messageType, String activeFlg, String createBy,
			Date createDate) {
		this.messageCode = messageCode;
		this.messageEn = messageEn;
		this.messageType = messageType;
		this.activeFlg = activeFlg;
	}

	public SysMessage(String messageCode, String messageEn, String messageTh, String messageType, String activeFlg,
			String createBy, Date createDate, String updateBy, Date updateDate) {
		this.messageCode = messageCode;
		this.messageEn = messageEn;
		this.messageTh = messageTh;
		this.messageType = messageType;
		this.activeFlg = activeFlg;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public String getMessageCode() {
		return this.messageCode;
	}

	public void setMessageCode(String messageCode) {
		this.messageCode = messageCode;
	}

	public String getMessageEn() {
		return this.messageEn;
	}

	public void setMessageEn(String messageEn) {
		this.messageEn = messageEn;
	}

	public String getMessageTh() {
		return this.messageTh;
	}

	public void setMessageTh(String messageTh) {
		this.messageTh = messageTh;
	}

	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(String activeFlg) {
		this.activeFlg = activeFlg;
	}

}
